import type { Metadata } from "next";
import Link from "next/link";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My store",
  description: "Generated by create next app",
};

function NavLinks() {
  return (
    <nav className="row-start-3 flex gap-6 flex-wrap items-center justify-center py-4 border-b border-t">
      <Link href="/">Home</Link>
      <Link href="/blog">Blog</Link>
      <Link href="/login">Login</Link>
    </nav>
  );
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <header>
            <NavLinks />
          </header>
          <div className="max-w-[1200px] mx-auto my-8">{children}</div>
          <footer>
            <NavLinks />
          </footer>
        </main>
      </body>
    </html>
  );
}
