import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavLinks from "@/ui/components/nav/nav";
import { Providers } from "./providers";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "My store",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Providers>
          <main>
            <header className="max-w-[1200px] mx-auto my-8 border-b pb-4">
              <NavLinks />
            </header>
            <div className="max-w-[1200px] mx-auto my-8">{children}</div>
            <footer className="max-w-[1200px] mx-auto my-8 border-t pt-4">
              <NavLinks />
            </footer>
          </main>
        </Providers>
      </body>
    </html>
  );
}
